version: 3.0.0.{build}-{branch}

branches:
  except:
    - gh-pages

install:
  - git submodule update --init --recursive

environment:
  matrix:
    - PRJ_GEN: "Visual Studio 17 2022"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2022"
      BDIR: msvc2022
      PRJ_CFG: Release
    #- PRJ_GEN: "Visual Studio 16 2019"
    #  APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    #  BDIR: msvc2019
    #  PRJ_CFG: Release

build_script:
  - mkdir build.%BDIR%
  - cd build.%BDIR%
  - cmake .. -G "%PRJ_GEN%" -A x64 "-DCMAKE_BUILD_TYPE=%PRJ_CFG%" %PARAMS%
  - cmake --build . --config "%PRJ_CFG%" --clean-first

test_script:
  - ctest -V --output-on-failure -C %PRJ_CFG%
